# ================================================
# QARA KARAKALPAKVOICE.ORG - ТИЛЛЕР КОНФИГУРАЦИЯСЫ
# ================================================

# 🇷🇺 РУССКИЙ ЯЗЫК (Дәслепки тил)
[ru]
title = "QARA Voice - Каракалпакский Голос"
description = "Независимый информационный портал Каракалпакстана. Новости, культура, история без цензуры."
languageName = "Русский"
languageCode = "ru"
weight = 1
contentDir = "content/ru"

[ru.params]
flag = "🇷🇺"
locale = "ru_RU"
direction = "ltr"
dateFormat = "2 January 2006"
timeFormat = "15:04"
currency = "₽"
timezone = "Europe/Moscow"

# Социаллық тармақлар орыс тилинде
[ru.params.social]
telegram = "https://t.me/kkvoice_org"
facebook = "https://www.facebook.com/share/1FifdzG23b/"
instagram = "https://www.instagram.com/karakalpakvoice_org/"
tiktok = "https://www.tiktok.com/@karakalpakvoice"
youtube = "https://youtube.com/@karakalpakvoice_org"
twitter = "https://x.com/Karakalpak45997"

# Байланыс мағлыўматы
[ru.params.contact]
email = "admin@karakalpakvoice.org"
phone = "+48 ххх ххх ххх"
address = "Варшава, Польша"
workingHours = "24/7"

# SEO орыс тилинде
[ru.params.seo]
keywords = ["Каракалпакстан", "новости", "суверенитет", "культура", "язык", "QARA"]
ogImage = "/images/og-ru.png"
twitterImage = "/images/twitter-ru.png"

# ================================================================

# 🏳️ ҚАРАҚАЛПАҚША (Негизги тил)
[kk]
title = "QARA Voice - Қарақалпақ Даўысы"
description = "Қарақалпақстанның ғәрезсиз мәлиметлер порталы. Цензурасыз жаңалықлар, мәденият, тарийх."
languageName = "Қарақалпақша" 
languageCode = "kk"
weight = 2
contentDir = "content/kk"

[kk.params]
flag = "🏳️"
locale = "kk_KZ"
direction = "ltr"
dateFormat = "2006 жылы 2 January"
timeFormat = "15:04"
currency = "₸"
timezone = "Asia"

# Социаллық тармақлар Қарақалпақша
[kk.params.social]
telegram = "https://t.me/kkvoice_org"
facebook = "https://www.facebook.com/share/1FifdzG23b/"
instagram = "https://www.instagram.com/karakalpakvoice_org/"
tiktok = "https://www.tiktok.com/@karakalpakvoice"
youtube = "https://youtube.com/@karakalpakvoice_org"
twitter = "https://x.com/Karakalpak45997"

# Байланыс мағлыўматы
[kk.params.contact]
email = "admin@karakalpakvoice.org"
phone = "+48 ххх ххх ххх"
address = "Варшава, Польша"
workingHours = "24/7"

# SEO қарақалпақша
[kk.params.seo]
keywords = ["Қарақалпақстан", "жаңалықлар", "суверенитет", "мәденият", "тил", "QARA"]
ogImage = "/images/og-kk.png"
twitterImage = "/images/twitter-kk.png"

# ================================================================

# 🇺🇸 ENGLISH (International)
[en]
title = "QARA Voice - Karakalpak Voice"
description = "Independent information portal of Karakalpakstan. Uncensored news, culture, and history."
languageName = "English"
languageCode = "en"
weight = 3
contentDir = "content/en"

[en.params]
flag = "🇺🇸"
locale = "en_US"
direction = "ltr"
dateFormat = "January 2, 2006"
timeFormat = "3:04 PM"
currency = "$"
timezone = "UTC"

# Social media in English
[en.params.social]
telegram = "https://t.me/kkvoice_org"
facebook = "https://www.facebook.com/share/1FifdzG23b/"
instagram = "https://www.instagram.com/karakalpakvoice_org/"
tiktok = "https://www.tiktok.com/@karakalpakvoice"
youtube = "https://youtube.com/@karakalpakvoice_org"
twitter = "https://x.com/Karakalpak45997"

# Contact information
[en.params.contact]
email = "admin@karakalpakvoice.org"
phone = "+48 ххх ххх ххх"
address = "Warsaw, Poland"
workingHours = "24/7"

# SEO in English
[en.params.seo]
keywords = ["Karakalpakstan", "news", "sovereignty", "culture", "language", "QARA"]
ogImage = "/images/og-en.png"
twitterImage = "/images/twitter-en.png"

# ================================================================

# 🇵🇱 POLSKI (Host country)
[pl]
title = "QARA Voice - Głos Karakałpacki"
description = "Niezależny portal informacyjny Karakałpakstanu. Nieuцenzurowane wiadomości, kultura, historia."
languageName = "Polski"
languageCode = "pl"
weight = 4
contentDir = "content/pl"

[pl.params]
flag = "🇵🇱"
locale = "pl_PL"
direction = "ltr"
dateFormat = "2 January 2006"
timeFormat = "15:04"
currency = "zł"
timezone = "Europe/Warsaw"

# Social media in Polish
[pl.params.social]
telegram = "https://t.me/kkvoice_org"
facebook = "https://www.facebook.com/share/1FifdzG23b/"
instagram = "https://www.instagram.com/karakalpakvoice_org/"
tiktok = "https://www.tiktok.com/@karakalpakvoice"
youtube = "https://youtube.com/@karakalpakvoice_org"
twitter = "https://x.com/Karakalpak45997"

# Contact information
[pl.params.contact]
email = "admin@karakalpakvoice.org"
phone = "+48 ххх ххх ххх"
address = "Warszawa, Polska"
workingHours = "24/7"

# SEO in Polish
[pl.params.seo]
keywords = ["Karakałpakstan", "wiadomości", "suwerenność", "kultura", "język", "QARA"]
ogImage = "/images/og-pl.png"
twitterImage = "/images/twitter-pl.png"

# ================================================================
# ҚОСЫМША ТИЛЛЕР (Келешекте қосыўға болады)
# ================================================================

# 🇰🇿 Қазақша (қоңсы тил)
# [uz]
# title = "QARA Voice - Қарақалпақстан үні"
# description = "Қарақалпақстан тәуелсіз ақпарат порталы. Цензурасыз жаңалықтар, мәдениет, тарих."
# languageName = "Қазақша"
# languageCode = "kz" 
# weight = 5
# contentDir = "content/kz"

# [uz.params]
# flag = "🇰🇿"
# locale = "ukz_KZ"
# direction = "ltr"

# ================================================================

# 🇫🇷 FRANÇAIS (Халықаралық)
# [fr]
# title = "QARA Voice - Voix Karakalpak"
# description = "Portail d'information indépendant du Karakalpakstan. Actualités, culture, histoire sans censure."
# languageName = "Français"
# languageCode = "fr"
# weight = 6
# contentDir = "content/fr"

# [fr.params]
# flag = "🇫🇷"
# locale = "fr_FR"
# direction = "ltr"

# ================================================================

# 🇩🇪 DEUTSCH (Халықаралық)
# [de]
# title = "QARA Voice - Karakalpakische Stimme"
# description = "Unabhängiges Informationsportal von Karakalpakstan. Unzensierte Nachrichten, Kultur, Geschichte."
# languageName = "Deutsch"
# languageCode = "de"
# weight = 7
# contentDir = "content/de"

# [de.params]
# flag = "🇩🇪"
# locale = "de_DE"
# direction = "ltr"

# ================================================================

# 🇹🇷 TÜRKÇE (Туўысқан тил)
# [tr]
# title = "QARA Voice - Karakalpak Sesi"
# description = "Karakalpakistan bağımsız bilgi portalı. Sansürsüz haberler, kültür, tarih."
# languageName = "Türkçe"
# languageCode = "tr"
# weight = 8
# contentDir = "content/tr"

# [tr.params]
# flag = "🇹🇷"
# locale = "tr_TR"
# direction = "ltr"

# ================================================================
# 🏳️ QARA VOICE - ҚАРАҚАЛПАҚСТАННЫҢ ДАЎЫСЫ
# ================================================================
# Версия: 1.0.0
# Тил файлы: languages.toml
# 4 негізгі тіл + 5 қосымша тил таярлығы
# ================================================================
