# ================================================
# QARA KARAKALPAKVOICE.ORG - МЕНЮ КОНФИГУРАЦИЯСЫ
# ================================================

# 📋 ТИЙКАРҒЫ МЕНЮ (барлық тиллер ушын)
[[main]]
identifier = "home"
name = "Бас"
pageRef = "/"
weight = 10
[main.params]
icon = "🏠"
description = "Бас бет"

[[main]]
identifier = "news" 
name = "Жаңалықлар"
pageRef = "/news"
weight = 20
[main.params]
icon = "📰"
description = "Соңғы жаңалықлар"

[[main]]
identifier = "sovereignty"
name = "Суверенитет" 
pageRef = "/sovereignty"
weight = 30
[main.params]
icon = "🏛️"
description = "Қарақалпақстан суверенитети"

[[main]]
identifier = "history"
name = "Тарийх"
pageRef = "/history" 
weight = 40
[main.params]
icon = "📚"
description = "Тарихый мақалалар"

[[main]]
identifier = "culture"
name = "Мәденият"
pageRef = "/culture"
weight = 50
[main.params]
icon = "🎭"
description = "Мәденият және дәстүрлер"

[[main]]
identifier = "geography"
name = "География" 
pageRef = "/geography"
weight = 60
[main.params]
icon = "🌍"
description = "Географиялық мағлыўматлар"

[[main]]
identifier = "religion"
name = "Дин"
pageRef = "/religion"
weight = 70
[main.params]
icon = "🕌"
description = "Дин туўралы мақалалар"

[[main]]
identifier = "sport"
name = "Спорт"
pageRef = "/sport"
weight = 80
[main.params]
icon = "⚽"
description = "Спорт жаңалықлары"

# ================================================================

# 📱 МОБИЛ МЕНЮ.(Қысқартылған)
[[mobile]]
identifier = "home-mobile"
name = "Бас"
pageRef = "/"
weight = 10

[[mobile]]
identifier = "news-mobile"
name = "Жаңалықлар"
pageRef = "/news"
weight = 20

[[mobile]]
identifier = "sovereignty-mobile"
name = "Суверенитет"
pageRef = "/sovereignty" 
weight = 30

[[mobile]]
identifier = "culture-mobile"
name = "Мәденият"
pageRef = "/culture"
weight = 40

[[mobile]]
identifier = "more-mobile"
name = "Тағы..."
pageRef = "#"
weight = 50
[mobile.params]
dropdown = true

# ================================================================

# 🔗 FOOTER МЕНЮ
[[footer]]
identifier = "about"
name = "Биз туўралы"
pageRef = "/about"
weight = 10
[footer.params]
icon = "ℹ️"

[[footer]]
identifier = "contact"
name = "Байланыс"
pageRef = "/contact"
weight = 20
[footer.params]
icon = "📧"

[[footer]]
identifier = "privacy"
name = "Қупыя"
pageRef = "/privacy"
weight = 30
[footer.params]
icon = "🔒"

[[footer]]
identifier = "terms"
name = "Шәртлер"
pageRef = "/terms"
weight = 40
[footer.params]
icon = "📋"

[[footer]]
identifier = "vpn-guide"
name = "VPN Guide"
pageRef = "/vpn-guide"
weight = 50
[footer.params]
icon = "🛡️"

[[footer]]
identifier = "security"
name = "Қәўипсизлик"
pageRef = "/security"
weight = 60
[footer.params]
icon = "🔐"

# ================================================================

# 👤 АВТОРЛАР меню
[[authors]]
identifier = "all-authors"
name = "Барлық авторлар"
pageRef = "/authors"
weight = 10

[[authors]]
identifier = "editors"
name = "Редакторлар"
pageRef = "/authors/editors"
weight = 20

[[authors]]
identifier = "contributors"
name = "Үлес қосыўшылар"
pageRef = "/authors/contributors"
weight = 30

[[authors]]
identifier = "join-team"
name = "Командаға қосылыў"
pageRef = "/join-team"
weight = 40

# ================================================================

# 📂 КАТЕГОРИЯ МЕНЮ
[[categories]]
identifier = "politics"
name = "Сиясат"
pageRef = "/categories/politics"
weight = 10
[categories.params]
icon = "⚖️"
color = "#FF6B35"

[[categories]]
identifier = "society"
name = "Жәмийет"
pageRef = "/categories/society"
weight = 20
[categories.params]
icon = "👥"
color = "#F7931E"

[[categories]]
identifier = "international"
name = "Халықаралық"
pageRef = "/categories/international"
weight = 30
[categories.params]
icon = "🌐"
color = "#4CAF50"

[[categories]]
identifier = "economy"
name = "Экономика"
pageRef = "/categories/economy"
weight = 40
[categories.params]
icon = "💼"
color = "#2196F3"

[[categories]]
identifier = "education"
name = "Билим"
pageRef = "/categories/education"
weight = 50
[categories.params]
icon = "🎓"
color = "#9C27B0"

[[categories]]
identifier = "health"
name = "Денсаўлық"
pageRef = "/categories/health"
weight = 60
[categories.params]
icon = "🏥"
color = "#E91E63"

# ================================================================

# 🔍 ҚОСЫМША МЕНЮ
[[tools]]
identifier = "search"
name = "Излеў"
pageRef = "/search"
weight = 10
[tools.params]
icon = "🔍"

[[tools]]
identifier = "archive"
name = "Архив"
pageRef = "/archive"
weight = 20
[tools.params]
icon = "📦"

[[tools]]
identifier = "tags"
name = "Теглер"
pageRef = "/tags"
weight = 30
[tools.params]
icon = "🏷️"

[[tools]]
identifier = "rss"
name = "RSS"
pageRef = "/index.xml"
weight = 40
[tools.params]
icon = "📡"
external = true

[[tools]]
identifier = "newsletter"
name = "Жазылыў"
pageRef = "/newsletter"
weight = 50
[tools.params]
icon = "📬"

# ================================================================

# 📱 СОЦИАЛЛЫҚ ТАРМАҚЛАР МЕНЮ
[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/kkvoice_org"
weight = 10
[social.params]
icon = "📱"
color = "#0088cc"
external = true

[[social]]
identifier = "facebook" 
name = "Facebook"
url = "https://www.facebook.com/share/1FifdzG23b/"
weight = 20
[social.params]
icon = "📘"
color = "#1877f2"
external = true

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/karakalpakvoice_org/"
weight = 30
[social.params]
icon = "📸"
color = "#E4405F"
external = true

[[social]]
identifier = "tiktok"
name = "TikTok"
url = "https://www.tiktok.com/@karakalpakvoice"
weight = 40
[social.params]
icon = "🎵"
color = "#000000"
external = true

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://youtube.com/@karakalpakvoice_org"
weight = 50
[social.params]
icon = "📹"
color = "#FF0000"
external = true

[[social]]
identifier = "twitter"
name = "Twitter/X"
url = "https://x.com/Karakalpak45997"
weight = 60
[social.params]
icon = "🐦"
color = "#1DA1F2"
external = true

# ================================================================

# 🎯 АРНАЙЫ МЕНЮ
[[special]]
identifier = "qr-download"
name = "QR код"
pageRef = "/qr"
weight = 10
[special.params]
icon = "📱"
qrcode = true

[[special]]
identifier = "pwa-install"
name = "Қосымша орнатыў"
pageRef = "#"
weight = 20
[special.params]
icon = "📲"
pwa = true

[[special]]
identifier = "dark-mode"
name = "Қараңғы режим"
pageRef = "#"
weight = 30
[special.params]
icon = "🌙"
toggle = true

[[special]]
identifier = "language-switcher"
name = "Тил таңлаў"
pageRef = "#"
weight = 40
[special.params]
icon = "🌍"
language = true

# ================================================================

# 🛡️ ҚӘЎИПСИЗЛИК МЕНЮ
[[security]]
identifier = "vpn-setup"
name = "VPN орнатыў"
pageRef = "/security/vpn"
weight = 10

[[security]]
identifier = "tor-guide"
name = "Tor браузери"
pageRef = "/security/tor"
weight = 20

[[security]]
identifier = "secure-messaging"
name = "Қәўипсиз хабарлама"
pageRef = "/security/messaging"
weight = 30

[[security]]
identifier = "digital-security"
name = "Санлы қәўипсизлик"
pageRef = "/security/digital"
weight = 40

[[security]]
identifier = "censorship-bypass"
name = "Цензураны айналып өтиў"
pageRef = "/security/bypass"
weight = 50

# ================================================================

# 🎓 БИЛИМ МЕНЮ
[[education]]
identifier = "karakalpak-language"
name = "Қарақалпақ тили"
pageRef = "/education/language"
weight = 10

[[education]]
identifier = "history-lessons"
name = "Тарийх сабақлары"
pageRef = "/education/history"
weight = 20

[[education]]
identifier = "culture-guide"
name = "Мәденият гид"
pageRef = "/education/culture"
weight = 30

[[education]]
identifier = "geography-atlas"
name = "География атласы"
pageRef = "/education/geography"
weight = 40

# ================================================================

# 📊 СТАТИСТИКА МЕНЮ (Админ ушын)
[[admin]]
identifier = "dashboard"
name = "Басқарыў тахтасы"
pageRef = "/admin"
weight = 10

[[admin]]
identifier = "analytics"
name = "Аналитика"
pageRef = "/admin/analytics"
weight = 20

[[admin]]
identifier = "content-management"
name = "Мазмун басқарыў"
pageRef = "/admin/content"
weight = 30

[[admin]]
identifier = "user-management"
name = "Пайдаланыўшылар"
pageRef = "/admin/users"
weight = 40

[[admin]]
identifier = "settings"
name = "Сазламалар"
pageRef = "/admin/settings"
weight = 50

# ================================================================
# 🏳️ QARA VOICE - ҚАРАҚАЛПАҚСТАННЫҢ ДАЎЫСЫ 
# ================================================================
# Версия: 1.0.0
# Меню файлы: menus.toml
# 10 меню түри: негізгі, мобил, footer, социаллық т.б.
# ================================================================
