baseURL = "https://karakalpakvoice.org"
languageCode = "ru"
title = "QARA Voice - Голос Каракалпакстана"
defaultContentLanguage = "ru"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Независимый медиа-портал Каракалпакстана"
