baseURL = "https://karol594.github.io/karakalpakvoice.org/"
languageCode = "kk"
title = "QARA Voice - Қарақалпақстан Даўысы"

enableRobotsTXT = true
enableEmoji = true
paginate = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  brand = "QARA Voice"
  description = "Қарақалпақстанның ғәрезсиз мәлимлеме порталы"
