# QARA VOICE - Қарапайым Hugo конфигурация
baseURL = "https://karol594.github.io/karakalpakvoice.org/"
languageCode = "kk"
title = "QARA Voice - Қарақалпақстан Даўысы"

# Hugo параметрлери
enableRobotsTXT = true
enableEmoji = true
paginate = 10

# Markup орнатпалары
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Тиллер
[languages]
  [languages.kk]
    languageCode = "kk"
    languageName = "Қарақалпақ"
    title = "QARA Voice - Қарақалпақстан Даўысы"
    weight = 1
    [languages.kk.params]
      description = "Қарақалпақстанның ғәрезсиз мәлимлеме порталы"

  [languages.ru]
    languageCode = "ru"
    languageName = "Русский"
    title = "QARA Voice - Голос Каракалпакстана"
    weight = 2
    [languages.ru.params]
      description = "Независимый медиа-портал Каракалпакстана"

# Меню
[menus]
  [[menus.main]]
    name = "Бас бет"
    url = "/"
    weight = 10
  [[menus.main]]
    name = "Мәлиметлер"
    url = "/news/"
    weight = 20
  [[menus.main]]
    name = "Мәденият"
    url = "/culture/"
    weight = 30
  [[menus.main]]
    name = "Биз туўралы"
    url = "/about/"
    weight = 40

# Параметрлер
[params]
  brand = "QARA Voice"
  description = "Қарақалпақстанның ғәрезсиз мәлимлеме порталы"
  author = "QARA Voice Team"
