# ================================================
# QARA KARAKALPAKVOICE.ORG – HUGO НЕГИЗГИ КОНФИГИ
# ================================================

baseURL = "https://karakalpakvoice.org"
title   = "QARA Voice – Қарақалпақ Дауысы"
description = "Қарақалпақстанның ғәрезсиз мәлимлеме порталы"
keywords    = ["Қарақалпақстан", "жаңалықлар", "суверенитет", "мәденият", "QARA"]

# Hugo версиясы
hugo_version = "0.120.0"

# Тил сазламасы
languageCode = "ru"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true

# Контент
contentDir = "content"
staticDir  = "static"
layoutDir  = "layouts"

# URL
canonifyURLs = true
relativeURLs = false
removePathAccents = true
disablePathToLower = false

# Пагинация
paginate      = 10
paginatePath  = "page"
summaryLength = 100
rssLimit      = 20

# Улыўма мүмкиншиликлер
enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true

# Markdown рендерер
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote       = true
      linkify        = true
      strikethrough  = true
      table          = true
      taskList       = true
      typographer    = true

  [markup.highlight]
    style             = "github"
    lineNos           = true
    codeFences        = true
    guessSyntax       = true
    lineNumbersInTable = false
    noClasses          = false
    tabWidth           = 4

# Таксономиялар
[taxonomies]
  tag      = "tags"
  category = "categories"
  author   = "authors"
  region   = "regions"

# Пост URL форматы
[permalinks]
  news        = "/news/:year/:month/:slug/"
  sovereignty = "/sovereignty/:slug/"
  history     = "/history/:slug/"
  culture     = "/culture/:slug/"
  geography   = "/geography/:slug/"
  religion    = "/religion/:slug/"
  sport       = "/sport/:slug/"
  authors     = "/authors/:slug/"
  pages       = "/:slug/"

# Sitemap
[sitemap]
  changefreq = "weekly"
  filename   = "sitemap.xml"
  priority   = 0.5

# Сервер
[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      X-Frame-Options           = "DENY"
      X-XSS-Protection         = "1; mode=block"
      X-Content-Type-Options   = "nosniff"
      Referrer-Policy          = "strict-origin-when-cross-origin"
      Content-Security-Policy  = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"

# Минимизация
[minify]
  disableCSS = false
  disableHTML = false
  disableJS  = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  
