# ================================
# Тил сазламалары – 4 тил
# ================================

[ru]
  languageName = "Русский"
  languageCode = "ru"
  contentDir = "content/ru"
  weight = 1
  [ru.params]
    flag = "🇷🇺"
    title = "QARA Voice — Каракалпакский Голос"
    description = "Независимый информационный портал Каракалпакстана — новости, культура, язык, суверенитет."

[kk]
  languageName = "Қарақалпақша"
  languageCode = "kk"
  contentDir = "content/kk"
  weight = 2
  [kk.params]
    flag = "🏳️"
    title = "QARA Voice — Қарақалпақ Дауысы"
    description = "Қарақалпақстанның гәрезсиз мәлиметлер порталы — жаңалықлар, мәденият, тил, суверенитет."

[en]
  languageName = "English"
  languageCode = "en"
  contentDir = "content/en"
  weight = 3
  [en.params]
    flag = "🇺🇸"
    title = "QARA Voice — Karakalpak Voice"
    description = "Independent information portal of Karakalpakstan — news, culture, language, sovereignty."

[pl]
  languageName = "Polski"
  languageCode = "pl"
  contentDir = "content/pl"
  weight = 4
  [pl.params]
    flag = "🇵🇱"
    title = "QARA Voice — Głos Karakałpacki"
    description = "Niezależny portal informacyjny Karakałpakstanu — wiadomości, kultura, język, suwerenność."
    
