# ================================================
# QARA VOICE - CMS КОНФИГУРАЦИЯ ФАЙЛЫ
# Netlify CMS (Decap CMS) орнатпалары
# ================================================

# Backend орнатпалары
backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

# Local development
local_backend: true

# Media орнатпалары
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# Site орнатпалары
site_url: https://karakalpakvoice.org
display_url: https://karakalpakvoice.org
logo_url: /images/logo-admin.png

# Editor орнатпалары
editor:
  preview: true

# Slug орнатпалары
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Collections (Контент түрлери)
collections:
  # ================================================
  # ЖАҢАЛЫҚЛАР / НОВОСТИ
  # ================================================
  - name: "news-ru"
    label: "📰 Новости (Русский)"
    folder: "content/ru/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Описание", name: "description", widget: "text"}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Автор", name: "author", widget: "string", default: "QARA Voice"}
      - {label: "Главное изображение", name: "featured_image", widget: "image", required: false}
      - {label: "Теги", name: "tags", widget: "list", required: false}
      - {label: "Категория", name: "category", widget: "select", options: ["политика", "общество", "экономика", "мир", "спорт"]}
      - {label: "Черновик", name: "draft", widget: "boolean", default: false}
      - {label: "Содержание", name: "body", widget: "markdown"}

  - name: "news-kk"
    label: "📰 Мәлиметлер (Қарақалпақ)"
    folder: "content/kk/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Атамасы", name: "title", widget: "string"}
      - {label: "Сыпатлама", name: "description", widget: "text"}
      - {label: "Жәрияланған күн", name: "date", widget: "datetime"}
      - {label: "Автор", name: "author", widget: "string", default: "QARA Voice"}
      - {label: "Негизги сүўрет", name: "featured_image", widget: "image", required: false}
      - {label: "Теглер", name: "tags", widget: "list", required: false}
      - {label: "Категория", name: "category", widget: "select", options: ["саясат", "қоғам", "экономика", "дүнья", "спорт"]}
      - {label: "Қоралама", name: "draft", widget: "boolean", default: false}
      - {label: "Мазмуны", name: "body", widget: "markdown"}

  - name: "news-en"
    label: "📰 News (English)"
    folder: "content/en/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "QARA Voice"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["politics", "society", "economy", "world", "sports"]}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Content", name: "body", widget: "markdown"}

  # ================================================
  # МӘДЕНИЯТ / КУЛЬТУРА
  # ================================================
  - name: "culture-ru"
    label: "🏛️ Культура (Русский)"
    folder: "content/ru/culture"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Описание", name: "description", widget: "text"}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Автор", name: "author", widget: "string", default: "QARA Voice"}
      - {label: "Главное изображение", name: "featured_image", widget: "image", required: false}
      - {label: "Теги", name: "tags", widget: "list", required: false}
      - {label: "Тип", name: "culture_type", widget: "select", options: ["традиции", "искусство", "литература", "музыка", "танцы", "ремесла"]}
      - {label: "Черновик", name: "draft", widget: "boolean", default: false}
      - {label: "Содержание", name: "body", widget: "markdown"}

  - name: "culture-kk"
    label: "🏛️ Мәденият (Қарақалпақ)"
    folder: "content/kk/culture"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Атамасы", name: "title", widget: "string"}
      - {label: "Сыпатлама", name: "description", widget: "text"}
      - {label: "Жарияланған күн", name: "date", widget: "datetime"}
      - {label: "Автор", name: "author", widget: "string", default: "QARA Voice"}
      - {label: "Негизги сүўрет", name: "featured_image", widget: "image", required: false}
      - {label: "Теглер", name: "tags", widget: "list", required: false}
      - {label: "Түри", name: "culture_type", widget: "select", options: ["салт-дәстүрлер", "өнер", "әдебият", "музыка", "бий", "қол өнер"]}
      - {label: "Қоралама", name: "draft", widget: "boolean", default: false}
      - {label: "Мазмуны", name: "body", widget: "markdown"}

  # ================================================
  # ТИЛ / ЯЗЫК
  # ================================================
  - name: "language-ru"
    label: "📚 Язык (Русский)"
    folder: "content/ru/language"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Описание", name: "description", widget: "text"}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Автор", name: "author", widget: "string", default: "QARA Voice"}
      - {label: "Главное изображение", name: "featured_image", widget: "image", required: false}
      - {label: "Теги", name: "tags", widget: "list", required: false}
      - {label: "Тип урока", name: "lesson_type", widget: "select", options: ["грамматика", "словарь", "произношение", "диалог", "культура речи"]}
      - {label: "Уровень", name: "level", widget: "select", options: ["начинающий", "средний", "продвинутый"]}
      - {label: "Черновик", name: "draft", widget: "boolean", default: false}
      - {label: "Содержание", name: "body", widget: "markdown"}

  - name: "language-kk"
    label: "📚 Тил (Қарақалпақ)"
    folder: "content/kk/language"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Атамасы", name: "title", widget: "string"}
      - {label: "Сыпатлама", name: "description", widget: "text"}
      - {label: "Жарияланған күн", name: "date", widget: "datetime"}
      - {label: "Автор", name: "author", widget: "string", default: "QARA Voice"}
      - {label: "Негизги сүўрет", name: "featured_image", widget: "image", required: false}
      - {label: "Теглер", name: "tags", widget: "list", required: false}
      - {label: "Сабақ түри", name: "lesson_type", widget: "select", options: ["грамматика", "сөз байлығы", "айтылыс", "диалог", "сөз мәдениятпы"]}
      - {label: "Дәрежеси", name: "level", widget: "select", options: ["башлаўшы", "орта", "жоқары"]}
      - {label: "Қоралама", name: "draft", widget: "boolean", default: false}
      - {label: "Мазмуны", name: "body", widget: "markdown"}

  # ================================================
  # БЕТЛЕР / СТРАНИЦЫ
  # ================================================
  - name: "pages-ru"
    label: "📄 Страницы (Русский)"
    folder: "content/ru"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Описание", name: "description", widget: "text"}
      - {label: "Дата создания", name: "date", widget: "datetime"}
      - {label: "Тип", name: "type", widget: "hidden", default: "page"}
      - {label: "Layout", name: "layout", widget: "select", options: ["single", "contact", "about"], default: "single"}
      - {label: "Черновик", name: "draft", widget: "boolean", default: false}
      - {label: "Содержание", name: "body", widget: "markdown"}

  - name: "pages-kk"
    label: "📄 Беттер (Қарақалпақ)"
    folder: "content/kk"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Атамасы", name: "title", widget: "string"}
      - {label: "Сыпатлама", name: "description", widget: "text"}
      - {label: "Жәрияланған күн", name: "date", widget: "datetime"}
      - {label: "Түри", name: "type", widget: "hidden", default: "page"}
      - {label: "Layout", name: "layout", widget: "select", options: ["single", "contact", "about"], default: "single"}
      - {label: "Қоралама", name: "draft", widget: "boolean", default: false}
      - {label: "Мазмуны", name: "body", widget: "markdown"}

  # ================================================
  # ОРНАТПАЛАР / НАСТРОЙКИ
  # ================================================
  - name: "settings"
    label: "⚙️ Орнатпалар / Настройки"
    files:
      - label: "Сайт орнатпалары"
        name: "site"
        file: "data/site.yml"
        fields:
          - {label: "Сайт атамасы", name: "title", widget: "string"}
          - {label: "Сыпатлама", name: "description", widget: "text"}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telegram", name: "telegram", widget: "string"}
          - {label: "Twitter", name: "twitter", widget: "string"}
          - {label: "Логотип", name: "logo", widget: "image"}
          - {label: "Фавикон", name: "favicon", widget: "image"}

      - label: "Меню орнатпалары"
        name: "menu"
        file: "data/menu.yml"
        fields:
          - label: "Негизги меню"
            name: "main"
            widget: "list"
            fields:
              - {label: "Атамасы", name: "name", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Салмағы", name: "weight", widget: "number"}
              - {label: "Белсенди", name: "active", widget: "boolean", default: true}

      - label: "Социал медиа"
        name: "social"
        file: "data/social.yml"
        fields:
          - {label: "Telegram канал", name: "telegram_channel", widget: "string"}
          - {label: "Telegram бот", name: "telegram_bot", widget: "string"}
          - {label: "Twitter", name: "twitter", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "YouTube", name: "youtube", widget: "string", required: false}
          - {label: "Instagram", name: "instagram", widget: "string", required: false}

# ================================================
# EDITOR ОРНАТПАЛАРЫ
# ================================================

# Editor тил орнатпалары
editor_workflow: false

# Preview орнатпалары
show_preview_links: true

# Media library орнатпалары
media_library:
  name: uploadcare
  config:
    publicKey: "демо_ключи"
    multiple: true
    tabs: "file camera url facebook gdrive dropbox instagram"
    effects: "crop,rotate,enhance,grayscale"
    imageShrink: "1920x1080"
    previewStep: true
    clearable: true

# ================================================
# QARA VOICE CMS КОНФИГУРАЦИЯ СОҢЫ
# ================================================
