# ================================================
# Netlify CMS – QARA KarakalpakVoice.ORG
# ================================================

backend:
  name: git-gateway
  branch: main
  repo: YOUR_USERNAME/karakalpakvoice.org

# Media & uploads
media_folder: "static/uploads"
public_folder: "/uploads"

# i18n
i18n:
  structure: multiple_folders
  locales: [ru, kk, en, pl]
  default_locale: ru

# Collections
collections:

  # 1. Жаңалықлар / News
  - name: "news"
    label: "🆕 Жаңалықлар / News"
    label_singular: "news"
    folder: "content/{{locale}}/news"
    create: true
    i18n: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{locale}}/news/{{year}}/{{month}}/{{slug}}"
    fields:
      - { label: "Title / Аты", name: "title", widget: "string", i18n: true }
      - { label: "Description", name: "description", widget: "text", i18n: true }
      - { label: "Keywords", name: "keywords", widget: "list", i18n: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: duplicate }
      - { label: "Publish Date", name: "date", widget: "datetime", i18n: duplicate }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", search_fields: ["title"], value_field: "title", i18n: duplicate }
      - { label: "Tags", name: "tags", widget: "list", i18n: true }
      - { label: "Category", name: "category", widget: "select", options: ["politics", "culture", "society", "international"], i18n: true }
      - { label: "Featured Image", name: "image", widget: "image", required: false, i18n: duplicate }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  # 2. Бетлер / Pages
  - name: "pages"
    label: "📄 Бетлер / Pages"
    label_singular: "page"
    folder: "content/{{locale}}/pages"
    create: true
    i18n: true
    slug: "{{slug}}"
    preview_path: "{{locale}}/{{slug}}"
    fields:
      - { label: "Title / Аты", name: "title", widget: "string", i18n: true }
      - { label: "Description", name: "description", widget: "text", i18n: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: duplicate }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  # 3. Авторлар / Authors
  - name: "authors"
    label: "👤 Авторлар / Authors"
    label_singular: "author"
    folder: "content/{{locale}}/authors"
    create: true
    i18n: true
    slug: "{{slug}}"
    preview_path: "{{locale}}/authors/{{slug}}"
    fields:
      - { label: "Name / Аты", name: "title", widget: "string", i18n: true }
      - { label: "Photo", name: "photo", widget: "image", required: false, i18n: duplicate }
      - { label: "Bio", name: "body", widget: "markdown", i18n: true }
      - { label: "Social Links", name: "social", widget: "object", i18n: true, fields: [
          { label: "Telegram", name: "telegram", widget: "string", required: false },
          { label: "Twitter", name: "twitter", widget: "string", required: false },
          { label: "Instagram", name: "instagram", widget: "string", required: false }
        ]}
        
