# ================================================
# GitHub Actions – Hugo → Netlify auto-deploy
# ================================================

name: Deploy Hugo Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository checkout
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2. Setup Hugo (extended)
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.0'
          extended: true

      # 3. Build Hugo
      - name: Build site
        run: hugo --minify

      # 4. Deploy to Netlify
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir public
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          
